capstoneproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('datasets.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

datasets/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from datasets import views
import simplejson

app_name= 'datasets'

urlpatterns = [
    # /
    url(r'^$', views.IndexView, name='index'),

    # /signup
    url(r'^signup/$', views.signup, name='signup'),

    # /signin
    url(r'^signin/$', views.signin, name='signin'),

    # /signout
    url(r'^signout/$', views.signout, name='signout'),

    # /api/datasets/
    url(r'^api/datasets/$', 
        views.DataSetList.as_view({'get': 'list', 'post': 'create'}), 
        name='dataset-list'
        ),
    url(r'^api/datasets/(?P<pk>[0-9]+)/$', 
        views.DataSetList.as_view({
            'get': 'retrieve', 'put': 'update', 
            'patch': 'partial_update', 'delete': 'destroy'
            }), 
        name='dataset-detail'
        ),

    # /user/1/
    url(r'^user/(?P<pk>[0-9]+)/$', views.ProfileView, name='profile'),

    # /user/1/edit
    url(r'^user/(?P<pk>[0-9]+)/edit/$', views.EditProfileView, name='editprofile'),

    # /user/1/changepassword
    url(r'^user/(?P<pk>[0-9]+)/password/$', views.ChangePasswordView, name='changepassword'),

    # /data/
    url(r'^data/$', views.DataView.as_view(), name='data'),

    # /data/1/
    url(r'^data/(?P<pk>[0-9]+)/$', views.DataDetailView, name='datadetail'),

    # /data/1/edit
    url(r'^data/(?P<pk>[0-9]+)/edit/$', views.EditDataSetView, name='editdataset'),

    # /data/1/download/json
    url(r'^data/(?P<pk>[0-9]+)/download/json/$', views.DownloadJsonView.as_view(), name='downloadJson'),

    # /data/1/download/csv
    url(r'^data/(?P<pk>[0-9]+)/download/csv/$', views.DownloadCsvView.as_view(), name='downloadCsv'),

    # /data/1/adddata
    url(r'^data/(?P<pk>[0-9]+)/adddata/$', views.AddDataView, name='adddata'),

    # /data/1/editrecord/1
    url(r'^data/(?P<pk>[0-9]+)/editrecord/(?P<number>[0-9]+)/$', views.editRecordView, name='editrecord'),

    # /data/1/deleterecord/1
    url(r'^data/(?P<pk>[0-9]+)/deleterecord/(?P<number>[0-9]+)/$', views.deleteRecordView, name='deleterecord'),

    # /mydata/
    url(r'^mydata/$', views.MyDataView, name='mydata'),

    # /newdata/
    url(r'^newdata/$', views.NewDataView, name='newdata'),

    # /newdata2/
    url(r'^newdata2/(?P<number>[0-9]+)/$', views.NewData2View, name='newdata2'),

    # /about/
    url(r'^team/$', views.AboutView, name='about'),

    # /whatwedo/
    url(r'^whatwedo/$', views.WhatWeDoView, name='whatwedo'),


    # # /data/1/getcsv/
    # url(r'^data/(?P<pk>[0-9]+)/getcsv/$', views.GetCsvView.as_view(), name='getcsv'),
    #
    # # /data/1/getjson/
    # url(r'^data/(?P<pk>[0-9]+)/getjson/$', views.GetJsonView.as_view(), name='getjson'),

]

urlpatterns = format_suffix_patterns(urlpatterns)

templates/base.html
<!DOCTYPE html>
<html class="no-js"> 
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	
	<title>{% block title %} HALANG: Datasets Portal{% endblock %}</title> {% load staticfiles %}

	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Template by FREEHTML5.CO" />
	<meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />
	<meta name="author" content="FREEHTML5.CO" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">
	<link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,300' rel='stylesheet' type='text/css'>
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<!-- Superfish -->
	<link rel="stylesheet" href="{% static 'css/superfish.css' %}">
	<link rel="stylesheet" href="{% static 'css/style1.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="{% static 'css/data.css' %}">
	<link rel="stylesheet" href="{% static 'css/table.css' %}">
	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->
<style>
  table,  th {
   
   border-collapse: separate;
   border-spacing: 15px;
 }

	* {
  box-sizing: border-box;
}

#myInput {
  background-image: url('{% static '/css/searchicon.png' %}');
  background-position: 10px 12px;
  background-repeat: no-repeat;
  width: 100%;
  font-size: 20px;
  padding: 12px 20px 12px 40px;
  border: 1px solid #ddd;
  margin-bottom: 12px;
}

input[type=text], input[type=password], input[type=email] {
    width: 100%;
    color: black;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}

/* Set a style for all buttons */
button {
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
}

/* Extra styles for the cancel button */
.cancelbtn {
    padding: 14px 20px;
    background-color: #f44336;
    width: 300px;
}

/* Float cancel and signup buttons and add an equal width */
.cancelbtn,.signupbtn {
    float: left;
    width: 50%;
}

/* Add padding to container elements */
.container {
    padding: 16px;
}

/* Clear floats */
.clearfix::after {
    content: "";
    clear: both;
    display: table;
}

/* Change styles for cancel button and signup button on extra small screens */
@media screen and (max-width: 300px) {
    .cancelbtn, .signupbtn {
       width: 100%;
    }
}
</style>
</head>

<body>
	<div id="fh5co-wrapper">
		<div id="fh5co-page">
			<div id="fh5co-header">
				<header id="fh5co-header-section">
					<div class="container">
						<div class="nav-header">
							<a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle"><i></i></a>
							<h1 id="fh5co-logo"><a href="{% url 'datasets:index' %}">HA<span>LANG</span></a></h1>
							<!-- START #fh5co-menu-wrap -->
							<nav id="fh5co-menu-wrap" role="navigation">
								<ul class="sf-menu" id="fh5co-primary-menu">
									<li>
										<a href="#" class="fh5co-sub-ddown">Datasets</a>
										<ul class="fh5co-sub-menu">
											<li><a href="{% url 'datasets:data' %}">Browse Datasets</a></li>
											{% if user.is_authenticated %}
											<li><a href="{% url 'datasets:newdata' %}">New Datasets</a></li>
											{% endif %}	
										</ul>
									</li>
									<li>
										<a href="#" class="fh5co-sub-ddown">About Us</a>
										<ul class="fh5co-sub-menu">
											<li><a href="{% url 'datasets:about' %}">The Team</a></li>
											<li><a href="{% url 'datasets:whatwedo' %}">What We Do</a></li>
										</ul>
									</li>
									{% if user.is_authenticated %}
									<li>
										<a class="fh5co-sub-ddown">{{ user.get_full_name }}</a>
										<ul class="fh5co-sub-menu">
											<li><a href="{% url 'datasets:profile' user.id %}">My Profile</a></li>
											<li><a href="{% url 'datasets:signout' %}">Signout</a></li>
										</ul>
									</li>
									{% else %}
									<li>
									<a class="fh5co-sub-ddown">Anonymous User</a>
										<ul class="fh5co-sub-menu">
											<li><a href="{% url 'datasets:signup' %}">Sign up</a></li>
											<li><a href="{% url 'datasets:signin' %}">Sign In</a></li>
										</ul>
									</li>
									{% endif %}
								</ul>
							</nav>
						</div>
					</div>
				</header>
			</div>
		
	{% block body %}
	{% endblock %}

<!-- fh5co-blog-section -->
<footer>
	<div id="footer">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-md-offset-3 text-center">
				</div>
			</div>
		</div>
	</div>
</footer>


	<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script type="text/javascript" src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script type="text/javascript" src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Stellar -->
	<script type="text/javascript" src="{% static 'js/jquery.stellar.min.js' %}"></script>
	<!-- Superfish -->
	<script type="text/javascript" src="{% static 'js/hoverIntent.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/superfish.js' %}"></script>

	<!-- Main JS (Do not remove) -->
	<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
	

	{% block js %}
	{% endblock %}

</body>
</html>

templates/changepassword.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}
<div class="fh5co-hero">
  <div class="fh5co-overlay"></div>
  <div class="fh5co-cover text-center" data-stellar-background-ratio="0.5" style="background-image: url({% static 'images/last.jpg' %});">
    <div class="desc animate-box">
      <h2>Change Passwords</h2>
      <span>Want to be secure and change your password? Just fill up the form below.</a></span>
    </div>
  </div>

</div>
<br>
<center><h2>Change Password Form</h2></center>
<form action="{% url 'datasets:changepassword' user.id %}" method="post" id="SignUpForm" role="form" style="border:1px solid #ccc">
  {% csrf_token %}
  <div class="container">
    {% for field in form.visible_fields %}

    <input type="password" placeholder="Enter your {{ field.label }}" id="id_{{ field.name }}" name="{{ field.name }}" required>

    {{ field.errors }}
    {% endfor %}

    <div class="clearfix">
      <center><button type="submit" class="btn waves-effect waves-light red darken-1">Save Changes</button>
      </div>
    </div>
  </form>
  {% endblock %}

templates/data.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}
<!-- STYLE OF SEARCH --> <style>   
* {
  box-sizing: border-box;
}

#myInput {
  background-position: 10px 12px;
  background-repeat: no-repeat;
  width: 100%;
  font-size: 16px;
  padding: 12px 20px 12px 40px;
  border: 1px solid #ddd;
  margin-bottom: 12px;
}
</style>

<!-- start of banner-->
<div class="fh5co-hero fh5co-hero-2">
 <div class="fh5co-overlay"></div>
 <div class="fh5co-cover fh5co-cover_2 text-center" data-stellar-background-ratio="0.5" style="background-image: url({% static 'images/sudy.jpg' %});">
  <div class="desc animate-box">
    <h2>Our currently available datasets</h2>
    <span>Below are datasets inputted by multiple users.</a></span>
  </div>
</div>
</div>
<!-- end of banner-->
<!-- end:header-top -->
<div id="fh5co-work-section">
 <div class="container">
  <div class="row">
   <div class="col-md-8 col-md-offset-2 text-center heading-section animate-box">
    <h3>Browse Datasets</h3>
  </div>
</div>
</div>

<!-- SEARCH -->
<input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for names.." title="Type in a name">



<!-- START OF DATASETS -->	
<div class="container">
  <div class="row">
   <main role="main" id="maincontent" class="content">
     <!-- Start of Title and Logo-->
     <div class="content-inner ">
       <ul id="ulm">   <!-- FOR SEARCH -->
         {% if all_dataset %}
         {% for dataset in all_dataset %}
         <li class="datasetslist-dataset">
          <a class="datasetslist-dataset-title-link" href="{% url 'datasets:datadetail' dataset.id %}">
            <img src="{% static 'images/pic6.jpg' %}" alt="Smiley face" style="float:left;height:130px;">

            <h3 class="datasetslist-dataset-title">{{ dataset.DataSet_Title }}</h3></a>
            <div class="datasetslist-dataset-files-icon">
              <div class="dataset-icon">  </a>
              </div>
            </div>
            <div class="datasetslist-dataset-metadata">
              <div class="contributor-list-container datasetslist-dataset-contributors">
                <ul class="contributor-list">
                 <li class="contributor-list-contributor" data-component="contributorTooltip">
                  <a href="{% url 'datasets:profile' dataset.DataSet_Poster.id %}">{{ dataset.DataSet_Poster.get_full_name }}</a>

                </li>
              </ul> 
            </div>
            <p>
              <span class="datasetslist-dataset-publish-date">{{ dataset.DataSet_Posted }} | Status: {{ dataset.DataSet_Status }}</span>
            </p>

            <div class="datasetslist-dataset-description">
              {{ dataset.DataSet_Description|slice:":143" }}...
            </div>
          </div>
          <br>
          <!-- END 1st DATASET -->
          {% endfor %}
          {% else %}
          <h3>We don't have any Datasets as of now... </h3>
          {% endif %}
        </div>
      </li>
    </div></div>
  </li>


</ul> <!-- END -->

<!-- END fh5co-work-section -->


</div>
<!-- END fh5co-wrapper -->

<!-- jQuery -->
<script>
  function myFunction() {
    var input, filter, ul, li, a, i;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    ul = document.getElementById("ulm");
    li = ul.getElementsByTagName("li");
    for (i = 0; i < li.length; i++) {
      a = li[i].getElementsByTagName("a")[0];
      if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
        li[i].style.display = "";
      } else {
        li[i].style.display = "none";

      }
    }
  }
</script>

{% endblock %}

templates/datadetail.html
{% extends 'base.html' %}
{% load staticfiles %}
}{% block body %}
<!-- STYLE OF table --><style>
* {
  box-sizing: border-box;
}

#myInput {
  background-position: 10px 12px;
  background-repeat: no-repeat;
  width: 100%;
  font-size: 16px;
  padding: 12px 20px 12px 40px;
  border: 1px solid #ddd;
  margin-bottom: 12px;
}


</style>

<!-- start of banner-->
<div class="fh5co-hero fh5co-hero-2">
 <div class="fh5co-overlay"></div>
 <div class="fh5co-cover fh5co-cover_2 text-center" data-stellar-background-ratio="0.5" style="background-image: url({% static 'images/sudy.jpg' %});">
  <div class="desc animate-box">
    <h2>{{ dataset.DataSet_Title }}</h2>
    <span>by {{ dataset.DataSet_Poster.get_full_name }} on {{ dataset.DataSet_Posted }}</a></span>
  </div>
</div>
</div>
<!-- end of banner-->
<!-- end:header-top -->
<div id="fh5co-work-section">
 <div class="container">
  <div class="row">
   <div class="col-md-8 col-md-offset-2 text-center heading-section animate-box">
    <h3>Dataset's Information</h3>
    {% if user == dataset.DataSet_Poster or request.user.is_superuser %}
    <a href="{% url 'datasets:editdataset' dataset.id %}">
      <button class="btn btn-primary" type="submit">Edit Dataset</button>
    </a>
    {% endif %}
  </div>
</div>
</div>

<!-- START OF DATASET -->   

<div class="container">
  <div class="row">
    <main role="main" id="maincontent" class="content">
     <!-- Start of Title and Logo-->
     <div class="content-inner ">
      <ul id="ulm">

        <li class="datasetslist-dataset">
          <a class="datasetslist-dataset-title-link" href="{% url 'datasets:datadetail' dataset.id %}">
            <img src="{% static 'images/pic6.jpg' %}" alt="Smiley face" style="float:left;height:130px;">
            <h3 class="datasetslist-dataset-title">{{ dataset.DataSet_Title }}</h3></a>
            <div class="datasetslist-dataset-files-icon">
              <div class="dataset-icon">  </a>
              </div>
            </div>

            <div class="datasetslist-dataset-metadata">
              <div class="contributor-list-container datasetslist-dataset-contributors">
                <ul class="contributor-list">
                 <li class="contributor-list-contributor" data-component="contributorTooltip">
                  <a href="{% url 'datasets:profile' dataset.DataSet_Poster.id %}">{{ dataset.DataSet_Poster.get_full_name }}</a>

                </li>
              </ul> 
            </div>
            <p>
              <span class="datasetslist-dataset-publish-date">{{ dataset.DataSet_Posted }} | Status: {{ dataset.DataSet_Status }}
                {% if request.user.is_superuser and dataset.DataSet_Status == 'Not yet Approved' %}
                <button onclick="approveDataSet()" class="btn btn-primary">Approve this Dataset</button>
                {% endif %}
              </span>
            </p>

            <div class="datasetslist-dataset-description">
              <p>{{ dataset.DataSet_Description }}</p>
              <p>This dataset has {{ count2 }} columns, namely the following: {{ colnames }}</p>
              <p>This dataset currently has {{ count }} records. The records are as the format: {{ rows|slice:":1" }}</p>
            </div>
          </div>
          <!-- End Of 1st Dataset-->
        </div>
      </li>
    </div></div>
  </li>

</ul> <!-- END OF DATA -->
<!-- END fh5co-work-section -->
</div>

{% if user == dataset.DataSet_Poster or request.user.is_superuser %}
<center>
  <a href="{% url 'datasets:adddata'  dataset.id %}">
    <button class="btn btn-primary" type="submit">Add Record</button>
  </a>
</center>
{% endif %}

<center><!-- TABLES-->
  <a href="{% url 'datasets:downloadCsv' dataset.id %}" download>
    <button class="btn btn-primary">Get CSV</button>
  </a>

  <a href="{% url 'datasets:dataset-detail' dataset.id %}">
    <button class="btn btn-primary">Goto API Endpoint</button>
  </a>

  <a href="{% url 'datasets:downloadJson' dataset.id %}" download>
    <button class="btn btn-primary">Get JSON</button>
  </a>
</center>
<style>
  table,  th {

   border-collapse: separate;
   border-spacing: 15px;
 }
</style>

<br><br><br>
<div class="container">
  <center><table style="width:80%">
    <thead>
      <tr>
        {% for i in colnames %}
        <th><center>{{i}}</center></th>
        {% endfor %}
        {% if user == dataset.DataSet_Poster or request.user.is_superuser %}
        <th><center>Actions</center></th>
        {% endif %}
      </tr>
    </thead>

    <tbody>
      {% for i in rows %}
      <tr>
        {% for o in i %}
        <td><center>{{o}}</center></td>
        {% endfor %}
        <td>
          {% if user == dataset.DataSet_Poster or request.user.is_superuser %}
          <center>
            <a href="{% url 'datasets:editrecord'  dataset.id forloop.counter %}">
              <button class="btn btn-primary">Edit Record</button>
            </a>
          </center>
          <center>
            <a href="{% url 'datasets:deleterecord'  dataset.id forloop.counter %}">
              <button class="btn btn-primary">Delete Record</button>
            </a>
          </center>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </center>
  <br>
</div>




{% endblock %}

{% block js %}
<script>
  $(document).ready(function(){
    var DataSetUrl = '/api/datasets/{{ dataset.id }}/';
    var datasetId = '{{ dataset.id }}';
    var json = '{{json}}';
    json = json.replace(/&#39;/g, "'")
    json = json.replace(/&quot;/g, '"').slice(2, -2)
    var params = {
      Data: "" + json,
      jsonifiedData_url: "https://hatopendatacatalog.herokuapp.com/data/{{ dataset.id }}/download/json/",
      csvfiedData_url: "https://hatopendatacatalog.herokuapp.com/data/{{ dataset.id }}/download/csv/"
    };

    $.ajax({
      type : 'PATCH',
      url : DataSetUrl,
      data : JSON.stringify(params),
      contentType: 'application/json',
      beforeSend: function(xhr, settings) {
        xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
      },
      success : function(json) {
      },
    });
  });
</script>

<script>
  function approveDataSet(){
    var approvedatasetUrl = '/api/datasets/{{ dataset.id }}/';
    if (confirm('Are you sure you want to approve this dataset?')){
      var params = {
        DataSet_Status: "Approved"
      };
      $.ajax({
        type: 'PATCH',
        url: approvedatasetUrl,
        data: JSON.stringify(params),
        contentType: 'application/json',
        beforeSend: function (xhr) {
          xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
        },
        success : function(json) {
          alert('Dataset is now approved!');
          window.location = '/data/{{ dataset.id }}';
        },
      });
    }
  }
</script>

{% endblock %}

templates/editprofile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}
<div class="fh5co-hero">
  <div class="fh5co-overlay"></div>
  <div class="fh5co-cover text-center" data-stellar-background-ratio="0.5" style="background-image: url({% static 'images/last.jpg' %});">
    <div class="desc animate-box">
      <h2>Edit Profile</h2>
      <span>Change your current profile and provide valid information for future purposes.</a></span>
    </div>
  </div>

</div>
<br>
<center><h2>Edit Profile Form</h2></center>
<form action="{% url 'datasets:editprofile' user.id %}" method="post" id="SignUpForm" role="form" style="border:1px solid #ccc">
  {% csrf_token %}
  <div class="container">
    <h2>First Name</h2>
    <input type="text" value="{{ user_form.first_name.value }}" id="id_{{ user_form.first_name.name }}" name="{{ user_form.first_name.name }}" required>
    <br><br>
    <h2>Last Name</h2>
    <input type="text" value="{{ user_form.last_name.value }}" id="id_{{ user_form.last_name.name }}" name="{{ user_form.last_name.name }}" required>
    <br><br>
    <h2>Email</h2>
    <input type="email" value="{{ user_form.email.value }}" id="id_{{ user_form.email.name }}" name="{{ user_form.email.name }}" required>
    <br><br>
    <h2>Biography</h2>
    <input type="text" value="{{ profile_form.bio.value }}" id="id_{{ profile_form.bio.name }}" placeholder="Short description of yourself" name="{{ profile_form.bio.name }}" required>
    <br><br>
    <h2>Location</h2>
    <input type="text" value="{{ profile_form.location.value }}" id="id_{{ profile_form.location.name }}" placeholder="Where you are currently located ex. Davao City" name="{{ profile_form.location.name }}" required>
    <br><br>
    <h2>Birth Date</h2>
    <input type="text" value="{{ profile_form.birth_date.value|date:'SHORT_DATE_FORMAT' }}" id="id_{{ profile_form.birth_date.name }}" placeholder="Follow the Format: MM/DD/YYYY ex. 11/07/1998" name="{{ profile_form.birth_date.name }}" required>
    <br><br>
    <h2>Associated with</h2>
    <input type="text" value="{{ profile_form.associated_with.value }}" id="id_{{ profile_form.associated_with.name }}" placeholder="Organization or School Name ex. University of the Immacualate Conception" name="{{ profile_form.associated_with.name }}" required>

    <div class="clearfix">
      <center><button type="submit" class="btn waves-effect waves-light red darken-1">Save Changes</button>
      </div>
    </div>
  </form>
  {% endblock %}

templates/newdata.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}
<div class="fh5co-hero">
  <div class="fh5co-overlay"></div>
  <div class="fh5co-cover text-center" data-stellar-background-ratio="0.5" style="background-image: url({% static 'images/pic69.jpg' %});">
    <div class="desc animate-box">
      <h2>Enter Your Datasets</h2>
      <span>Upload and share your research data for free, just fill up the form below to get started.</span>
    </div>
  </div>
</div>
<br>
<center><h2>New Dataset Form Part 1</h2></center>
<form action="{% url 'datasets:newdata' %}" method="post" style="border:1px solid #ccc" role="form">
  {% csrf_token %}
  <div class="container">
   <label><b></b></label>
   <input type="text" placeholder="Enter a Title for your Dataset" id="id_{{ form.DataSet_Title.name }}" name="{{ form.DataSet_Title.name }}" required>

   <label><b></b></label>
   <input type="text" placeholder="Enter a Description for your Dataset" id="id_{{ form.DataSet_Description.name }}" name="{{ form.DataSet_Description.name }}" required>

   <label><b></b></label>
   <input type="text" placeholder="Enter the number of columns you want for your Dataset" id="noofcolumns" name="noofcolumns" required>

   <div class="clearfix">
    <center><button type="submit" class="btn waves-effect waves-light red darken-1">Next</button>
    </div>
  </div>
  {% endblock %}

templates/signin.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}
<div class="fh5co-hero">
  <div class="fh5co-overlay"></div>
  <div class="fh5co-cover text-center" data-stellar-background-ratio="0.5" style="background-image: url({% static 'images/last.jpg' %});">
    <div class="desc animate-box">
      <h2>Sign in using your account now</h2>
      <span>Fill in the form below to sign in.</a></span>
    </div>
  </div>
</div>
<br>
<center><h2>Sign In Form</h2></center>
<form action="{% url 'datasets:signin' %}" method="post" style="border:1px solid #ccc" role="form">
  {% csrf_token %}
  <div class="container">
   <label><b></b></label>
   <input type="text" placeholder="Enter Username" id="id_{{ form.username.name }}" name="{{ form.username.name }}" required>

   <label><b></b></label>
   <input type="password" placeholder="Enter Password" id="id_{{ form.password.name }}" name="{{ form.password.name }}" required>

   <div class="clearfix">
    <center><button type="submit" class="btn waves-effect waves-light red darken-1">Sign In</button>
    </div>
  </div>

  {% endblock %}

templates/signout.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}
<div class="fh5co-hero">
  <div class="fh5co-overlay"></div>
  <div class="fh5co-cover text-center" data-stellar-background-ratio="0.5" style="background-image: url({% static 'images/last.jpg' %});">
    <div class="desc animate-box">
      <h2>You have signed out from our site.</h2>
      <span>Below are options to take you back to our home or sign back in.</a></span>
    </div>
  </div>

</div>
<br>
<center><h2>You have successfully Signed Out.</h2></center>
<main role="main" id="maincontent" class="content">
  <div class="content-inner ">
    <center><a href="{% url 'datasets:index' %}">Back to Home.</a></center>
    <center><a href="{% url 'datasets:signin' %}">Sign In.</a></center>
  </div>
</main>
{% endblock %}